config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charts, only: [:index, :create]

  root 'charts#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
require 'csv'

class ChartsController < ApplicationController

  def index
  end

  def create
    builder = ChartBuilderService.new(params[:input_file].tempfile)
    @builds_series = builder.builds_series
    @duration_series = builder.duration_series
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/create.html.slim
h1 Builds
= column_chart @builds_series, stacked: true, colors: ["#EB5A5A", "#7DEC97"]
h2 Duration
= column_chart @duration_series

app/views/charts/index.html.slim
= form_tag(charts_path, method: :post, multipart: true)
  .container
    br/
    .row
      .col-md-12
        .panel.panel-default
          .panel-heading
            strong Upload files
            small
          .panel-body
            .input-group.file-preview
              input.form-control.file-preview-filename name='file_name' disabled="disabled" placeholder="" type="text" /
              span.input-group-btn
                button.btn.btn-default.file-preview-clear style="display:none;" type="button"
                  span.glyphicon.glyphicon-remove
                  | Clear
              .btn.btn-default.file-preview-input
                span.glyphicon.glyphicon-folder-open
                span.file-preview-input-title Browse
                input onchange="fileSelect(event)" name="input_file" type="file" /
              button.btn.btn-labeled.btn-primary type="submit"
                span.btn-label
                  i.glyphicon.glyphicon-upload
                | Upload
            br/

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cyber</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>